### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by jiawenzhou11** [ShengyuH/OverlapPredator#10]
when I run the code "python main.py configs/train/indoor.yaml",  got error"ModuleNotFoundError: No module named 'cpp_wrappers.cpp_neighbors.radius_neighbors'".

**Comment by jiawenzhou11** [comment]
Are there any files lost?

**Comment by zgojcic** [comment]
You have to compile the cpp_wrappers using the following code:

`cd cpp_wrappers
sh compile_wrappers.sh
cd ..`

**Comment by jiawenzhou11** [comment]
> You have to compile the cpp_wrappers using the following code:
> 
> ```
> cd cpp_wrappers;
> sh compile_wrappers.sh;
> cd .. 
> ```

Thanks for your reply.
