### ISSUE TITLE
Cannot call the C++ methods

### ISSUE THREAD

**Issue by chenyuxin0629** [ShengyuH/OverlapPredator#11]
Hi!Thanks for your great work! After I run the command: sh compile_wrappers.sh,I got the .so files, and It seems that I have successfully compiled the C++ extension module for python located in `cpp_wrappers`. But when debug,I still get the AttributeError: module 'cpp_wrappers.cpp_neighbors.neighbors' has no attribute 'batch_query'.Do you know what this is about?
Thank you very much!

**Comment by ShengyuH** [comment]
Can you delete the build folder and *.so files and recompile it?

**Comment by chenyuxin0629** [comment]
> Can you delete the build folder and *.so files and recompile it?

Thanks a lot! It works!

**Comment by LFX99** [comment]
> Can you delete the build folder and *.so files and recompile it?

Sorry, What does this “*.” mean,I'm running 'build.bat' this file,but it still have the same problem.

**Comment by liyuan123-1** [comment]
> 你好！感谢您的出色工作！在我运行命令：sh compile_wrappers.sh后，我得到了.so文件，并且似乎已经成功编译了位于中的python的C++扩展模块。但是在调试时，我仍然得到属性错误：模块"cpp_wrappers.cpp_neighbors.neighbors"没有属性"batch_query"。你知道这是关于什么的吗？ 谢谢！`cpp_wrappers`

您好，我在运行程序时遇到了相同的问题，显示cpp_wrappers.cpp_neighbors.neighbors' has no attribute 'batch_query'，请问您当时是怎么解决的呢？

**Comment by ShengyuH** [comment]
Please try to delete the build folder and all *.so files and recompile it.

**Comment by liyuan123-1** [comment]
感谢您的回复，但是目前我还没有解决，可能我哪个环节出错了，我再去看一看。

**Comment by wxr997** [comment]
> 感谢您的回复，但是目前我还没有解决，可能我哪个环节出错了，我再去看一看。

请问您有解决吗，我也遇见了同样的问题！
