### ISSUE TITLE
Why should I use the .pth file for the demo?

### ISSUE THREAD

**Issue by Grungeby52** [ShengyuH/OverlapPredator#2]
Hi,
 
I have files with .ply or .pcd extension for demo. How can i convert them to .pth format and use them?

Best Regards

**Comment by ShengyuH** [comment]
hi,

We use .pth file for efficient IO during training. You can simply modify the dataloader here: https://github.com/ShengyuH/OverlapPredator/blob/ebf7595b95aa4e21a9294f3b2a85d0dad237b3ac/scripts/demo.py#L48 for your demo. In your case, please consider using open3d to read your point clouds: http://www.open3d.org/docs/release/python_api/open3d.io.read_point_cloud.html. Additionally, please also specify your data path in Line88 and Line89 in config.py. 

Thank you for your interest and please let me know if this solves the problem.

Best,
Shengyu

**Comment by Grungeby52** [comment]
Hi,

Thanks for the quick response,
I applied it as you said;

        src_pcd = o3d.io.read_point_cloud("/home/san/Desktop/OverlapPredator-main/figures/Model11.ply")
        xyz_load_src= np.asarray(src_pcd.points).astype(np.float32)

        tgt_pcd = o3d.io.read_point_cloud("/home/san/Desktop/OverlapPredator-main/figures/Model15.ply")
        xyz_load_tgt= np.asarray(tgt_pcd.points).astype(np.float32)

        src_pcd=xyz_load_src
        tgt_pcd=xyz_load_tgt

It worked but I guess GPU memory was insufficient. Batch size already 1

RuntimeError: CUDA out of memory. Tried to allocate 1.06 GiB (GPU 0; 3.95 GiB total capacity; 1.89 GiB already allocated; 593.50 MiB free; 2.36 GiB reserved in total by PyTorch)

I'm not exactly sure what to do right now...

Best Regards,
Onur Güzeldemirci

**Comment by ShengyuH** [comment]
Hi,

Yes it seems you don't have enough GPU memory. The Transformer used in our overlap attention module is memory hungry, I guess the only fix would be upgrading your hardware. We only test our models on GPUs with at least 12GB ram. 

Best,
Shengyu
