### ISSUE TITLE
Missing file in indoor test dataset

### ISSUE THREAD

**Issue by anhquancao** [ShengyuH/OverlapPredator#4]
Hello,

Thank you for your work.

I ran your evaluation script 
`python main.py configs/test/indoor.yaml`
and got an error 
`FileNotFoundError: [Errno 2] No such file or directory: 'data/indoor/test/7-scenes-redkitchen/cloud_bin_21.pth'`

I noticed that there is a file with the same name in the folder assets. Is it the same file?

Thank you very much for your help

**Comment by ShengyuH** [comment]
hi,

Your catch is totally right, I mistakenly ```mv``` these two files to assets folders. I think both bin 21 and bin 34 are missing in provided data. I will update the provided data later. For now you can just ```cp``` those two files from assets. 

Best,
Shengyu

**Comment by shrinivas96** [comment]
It still does not seem like the files are present here. I get the error `FileNotFoundError: [Errno 2] No such file or directory: 'data/indoor/train/rgbd-scenes-v2-scene_01/cloud_bin_1.pth'` after running `python scripts/demo.py configs/test/indoor.yaml` taken from the [demo section](https://github.com/prs-eth/OverlapPredator#demo) of the main page. The file that it wants are also not present in the `assests` folder.
