### ISSUE TITLE
voxel-grid subsampled

### ISSUE THREAD

**Issue by fukexue** [ShengyuH/OverlapPredator#6]
I'm sorry to disturb you. I'd like to know what grid size is used in your data preprocessing? I am looking forward to your reply, or whether it is convenient to provide data preprocessing code.

**Comment by ShengyuH** [comment]
hi,

I am using 2.5cm and 30cm for 3DMatch and odometryKITTI datasets.

**Comment by ShengyuH** [comment]
> I'm sorry to disturb you. I'd like to know what grid size is used in your data preprocessing? I am looking forward to your reply, or whether it is convenient to provide data preprocessing code.

hi, regarding the preprocessing file, since we might have different organisations of raw data, we don't intend to publish it. But all we did is doing voxel-grid downsampling with MinkowskiEngine. Please let me know if this addresses your problems.
