### ISSUE TITLE
invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26

### ISSUE THREAD

**Issue by joy-yjl** [ShengyuH/OverlapPredator#8]
I try to train your model with modelnet40 dataset ,bug I got a hit "invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:26". 
Did you meet the same issue?   When I test modelnet ckpt with my own dataset, I got same error. Do you know why?

**Comment by ShengyuH** [comment]
hi, 

The bug occurs when you have less than 10 superpoints in the bottleneck(then the DGCNN part fails). Please consider adjusting k here:   https://github.com/ShengyuH/OverlapPredator/blob/9772bb65fc06b9f576054620a3a2da7a49d4ace7/configs/test/modelnet.yaml#L32

We use try/catch scheme to skip these pairs in our experiments.

**Comment by joy-yjl** [comment]
> hi,
> 
> The bug occurs when you have less than 10 superpoints in the bottleneck(then the DGCNN part fails). Please consider adjusting k here:
> 
> https://github.com/ShengyuH/OverlapPredator/blob/9772bb65fc06b9f576054620a3a2da7a49d4ace7/configs/test/modelnet.yaml#L32
> 
> We use try/catch scheme to skip these pairs in our experiments.


Thanks for your reply. I change dfcnn_k to 0, but it is useless . I fix that by change  first_subsampling_dl to 0.01.  The bug maybe caused by subsampling.

**Comment by ShengyuH** [comment]
hi,

Please be really careful when changing first_subsampling_dl value. This determines the effective receptive field and thus the final performance.

**Comment by ShengyuH** [comment]
Please reopen this issue if your find further questions
